version: '3.8'

services:

  jenkins:
    build: .
    container_name: jenkins-bluocean
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - 'DOCKER_HOST=tcp://docker:2376'
      - 'DOCKER_CERT_PATH=/certs/client'
      - 'DOCKER_TLS_VERIFY=1'
    ports:
      - '8080:8080'
      - '50000:50000'
  
  docker:
    image: docker:dind 
    container_name: jenkins-docker
    privileged: true
    environment:
      - 'DOCKER_TLS_CERTDIR=/certs'
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    ports:
      - '2376:2376'
volumes:
  enkins-data:
  jenkins-docker-certs:
